global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: great_memories_api
    static_configs:
      - targets: ['great-memories-server:8081']

  - job_name: great_memories_microservices
    static_configs:
      - targets: ['great-memories-server:8082']
