[tools]
python = "3.11"
uv = "0.8.15"

[tasks.install]
run = "uv sync --locked"

[tasks.lint]
run = "uv run ruff check great_memories_ml"

[tasks.test]
run = "uv run pytest --cov=great_memories_ml --cov-report term-missing"

[tasks.format]
run = "uv run ruff format great_memories_ml"

[tasks.check]
run = "uv run mypy --strict great_memories_ml/"

[tasks.ci-unit]
run = [
  { task = ":install --extra cpu" },
  { task = ":format" },
  { task = ":lint --output-format=github" },
  { task = ":check" },
  { task = ":test" },
]

[tasks.checklist]
run = [
  { task = ":install" },
  { task = ":format" },
  { task = ":lint" },
  { task = ":check" },
  { task = ":test" },
]
